/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.section3;

/**
 *
 * @author jamesmurphy
 */
public class Section3Panel extends javax.swing.JPanel {

    /**
     * Creates new form Section3Panel
     */
    public Section3Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblS3Title = new javax.swing.JLabel();
        pnlS3Controls = new javax.swing.JPanel();
        pnlS3SortRow = new javax.swing.JPanel();
        lblS3Sort = new javax.swing.JLabel();
        cboS3Sort = new javax.swing.JComboBox<>();
        pnlS3Filters = new javax.swing.JPanel();
        pnlS3FiltersRow = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        chkS3Renewable100 = new javax.swing.JCheckBox();
        chkS3Renewable50to90 = new javax.swing.JCheckBox();
        chkS3OverallCheapest = new javax.swing.JCheckBox();
        chkS3BestNight = new javax.swing.JCheckBox();
        chkS3BestDay = new javax.swing.JCheckBox();
        chkS3BestFlat = new javax.swing.JCheckBox();
        chkS3HighUsage = new javax.swing.JCheckBox();
        chkS3LowUsage = new javax.swing.JCheckBox();
        ClearBtnS3Container = new javax.swing.JPanel();
        btnS3ClearFilters = new javax.swing.JButton();
        scrollPaneS3Container = new javax.swing.JPanel();
        scrS3Tariffs = new javax.swing.JScrollPane();
        tariffS3Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblS3Title.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblS3Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblS3Title.setText("Go Green Tariff Comparison");

        pnlS3Controls.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlS3SortRow.setLayout(new java.awt.GridLayout(1, 2));

        lblS3Sort.setText("Sort");
        pnlS3SortRow.add(lblS3Sort);

        cboS3Sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lowest cost", "Greenest", "Lowest CO2" }));
        pnlS3SortRow.add(cboS3Sort);

        javax.swing.GroupLayout pnlS3ControlsLayout = new javax.swing.GroupLayout(pnlS3Controls);
        pnlS3Controls.setLayout(pnlS3ControlsLayout);
        pnlS3ControlsLayout.setHorizontalGroup(
            pnlS3ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlS3ControlsLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pnlS3SortRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        pnlS3ControlsLayout.setVerticalGroup(
            pnlS3ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlS3ControlsLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pnlS3SortRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlS3Filters.setBorder(javax.swing.BorderFactory.createTitledBorder("Filters"));

        pnlS3FiltersRow.setLayout(new javax.swing.BoxLayout(pnlS3FiltersRow, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout(2, 4));

        chkS3Renewable100.setText("100% renewable only");
        jPanel1.add(chkS3Renewable100);

        chkS3Renewable50to90.setText("50% to 90% renewable");
        jPanel1.add(chkS3Renewable50to90);

        chkS3OverallCheapest.setText("Overall cheapest");
        jPanel1.add(chkS3OverallCheapest);

        chkS3BestNight.setText("Best for nighttime");
        chkS3BestNight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkS3BestNightActionPerformed(evt);
            }
        });
        jPanel1.add(chkS3BestNight);

        chkS3BestDay.setText("Best for daytime");
        jPanel1.add(chkS3BestDay);

        chkS3BestFlat.setText("Best flat rate");
        jPanel1.add(chkS3BestFlat);

        chkS3HighUsage.setText("High energy usage");
        jPanel1.add(chkS3HighUsage);

        chkS3LowUsage.setText("Low energy usage");
        jPanel1.add(chkS3LowUsage);

        pnlS3FiltersRow.add(jPanel1);

        pnlS3Filters.add(pnlS3FiltersRow);

        ClearBtnS3Container.setLayout(new javax.swing.BoxLayout(ClearBtnS3Container, javax.swing.BoxLayout.LINE_AXIS));

        btnS3ClearFilters.setText("Clear");
        ClearBtnS3Container.add(btnS3ClearFilters);

        scrS3Tariffs.setBorder(javax.swing.BorderFactory.createTitledBorder("Tariffs"));

        jLabel1.setText("Placeholder Text");

        jLabel2.setText("Placeholder Text");

        jLabel3.setText("Placeholder Text");

        jLabel4.setText("Placeholder Text");

        jLabel5.setText("Placeholder Text");

        javax.swing.GroupLayout tariffS3PanelLayout = new javax.swing.GroupLayout(tariffS3Panel);
        tariffS3Panel.setLayout(tariffS3PanelLayout);
        tariffS3PanelLayout.setHorizontalGroup(
            tariffS3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tariffS3PanelLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addGroup(tariffS3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(334, Short.MAX_VALUE))
        );
        tariffS3PanelLayout.setVerticalGroup(
            tariffS3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tariffS3PanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        scrS3Tariffs.setViewportView(tariffS3Panel);

        javax.swing.GroupLayout scrollPaneS3ContainerLayout = new javax.swing.GroupLayout(scrollPaneS3Container);
        scrollPaneS3Container.setLayout(scrollPaneS3ContainerLayout);
        scrollPaneS3ContainerLayout.setHorizontalGroup(
            scrollPaneS3ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scrollPaneS3ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrS3Tariffs, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        scrollPaneS3ContainerLayout.setVerticalGroup(
            scrollPaneS3ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scrollPaneS3ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrS3Tariffs, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblS3Title, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlS3Controls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ClearBtnS3Container, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlS3Filters, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scrollPaneS3Container, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblS3Title, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlS3Controls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(pnlS3Filters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClearBtnS3Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(scrollPaneS3Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkS3BestNightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkS3BestNightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkS3BestNightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClearBtnS3Container;
    private javax.swing.JButton btnS3ClearFilters;
    private javax.swing.JComboBox<String> cboS3Sort;
    private javax.swing.JCheckBox chkS3BestDay;
    private javax.swing.JCheckBox chkS3BestFlat;
    private javax.swing.JCheckBox chkS3BestNight;
    private javax.swing.JCheckBox chkS3HighUsage;
    private javax.swing.JCheckBox chkS3LowUsage;
    private javax.swing.JCheckBox chkS3OverallCheapest;
    private javax.swing.JCheckBox chkS3Renewable100;
    private javax.swing.JCheckBox chkS3Renewable50to90;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblS3Sort;
    private javax.swing.JLabel lblS3Title;
    private javax.swing.JPanel pnlS3Controls;
    private javax.swing.JPanel pnlS3Filters;
    private javax.swing.JPanel pnlS3FiltersRow;
    private javax.swing.JPanel pnlS3SortRow;
    private javax.swing.JScrollPane scrS3Tariffs;
    private javax.swing.JPanel scrollPaneS3Container;
    private javax.swing.JPanel tariffS3Panel;
    // End of variables declaration//GEN-END:variables
}
