/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author jamesmurphy
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    public void goLanding() {
        tabsMain.setSelectedIndex(0);
    }
    
    public void goSection1() {
        tabsMain.setSelectedIndex(1);
    }
    
    public void goSection2() {
        tabsMain.setSelectedIndex(2);
    }
    
    public void goSection3() {
        tabsMain.setSelectedIndex(3);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabsMain = new javax.swing.JTabbedPane();
        Landing = new javax.swing.JPanel();
        landingPanel1 = new ui.LandingPanel();
        Section1 = new javax.swing.JPanel();
        section1Panel2 = new ui.section1.Section1Panel();
        Section2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        section2Panel1 = new ui.section2.Section2Panel();
        Section3 = new javax.swing.JPanel();
        section3Panel1 = new ui.section3.Section3Panel();
        section3Panel2 = new ui.section3.Section3Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabsMain.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        javax.swing.GroupLayout LandingLayout = new javax.swing.GroupLayout(Landing);
        Landing.setLayout(LandingLayout);
        LandingLayout.setHorizontalGroup(
            LandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(landingPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        LandingLayout.setVerticalGroup(
            LandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(landingPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        tabsMain.addTab("Landing", Landing);

        Section1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Section1.add(section1Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 590, 433));

        tabsMain.addTab("Usage & Cost", Section1);

        Section2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(section2Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(section2Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Section2.add(jPanel1, java.awt.BorderLayout.CENTER);

        tabsMain.addTab("Usage Slider", Section2);

        javax.swing.GroupLayout section3Panel1Layout = new javax.swing.GroupLayout(section3Panel1);
        section3Panel1.setLayout(section3Panel1Layout);
        section3Panel1Layout.setHorizontalGroup(
            section3Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, section3Panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(section3Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        section3Panel1Layout.setVerticalGroup(
            section3Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(section3Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(section3Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Section3Layout = new javax.swing.GroupLayout(Section3);
        Section3.setLayout(Section3Layout);
        Section3Layout.setHorizontalGroup(
            Section3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Section3Layout.createSequentialGroup()
                .addComponent(section3Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Section3Layout.setVerticalGroup(
            Section3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Section3Layout.createSequentialGroup()
                .addComponent(section3Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsMain.addTab("GoGreen Tariffs", Section3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsMain, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tabsMain.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Landing;
    private javax.swing.JPanel Section1;
    private javax.swing.JPanel Section2;
    private javax.swing.JPanel Section3;
    private javax.swing.JPanel jPanel1;
    private ui.LandingPanel landingPanel1;
    private ui.section1.Section1Panel section1Panel2;
    private ui.section2.Section2Panel section2Panel1;
    private ui.section3.Section3Panel section3Panel1;
    private ui.section3.Section3Panel section3Panel2;
    private javax.swing.JTabbedPane tabsMain;
    // End of variables declaration//GEN-END:variables
}
