/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.section1;

import javax.swing.JOptionPane;

/**
 *
 * @author jamesmurphy
 */
public class Section1Panel extends javax.swing.JPanel {

    /**
     * Creates new form Section1Panel
     */
    
    //variables
    // form 1
    private String s1KwhPeriod;
    private String s1NightRate;
    private String s1DayRate;
    private String s1FlatRate;
    private String s1Period;
    
    private boolean s1IncludeVat;
    private boolean s1IncludeStandingCharge;
    private boolean s1IncludePsoLevy;

    // declare variables, used for parsing inputs to double
    private double s1KwhPeriodValue; 
    private double s1DayRateValue;
    private double s1NightRateValue;
    private double s1FlatRateValue;
    
    //form 2
    private String s1EnergySetup;
    private int s1PeopleCount;
    private String s1NightPercentChoice;
    
    private int s1NightPercentValue; //for parsing s1NightPercentChoice to int
    
    private String s1PrimaryHeatingChoice;
    private boolean s1PrimaryHeatingElectric;

    //constructor       
    public Section1Panel() {
        initComponents();
        
 
        //hides fields until set to true
        //form 1 
        s1DayRateTf.setVisible(false); 
        s1NightRateTf.setVisible(false);
        s1FlatRateTf.setVisible(false);
        s1UnitRateVatCb.setVisible(false);
        s1StandingChargeCb.setVisible(false);
        s1PsoLevyCb.setVisible(false);
        
        //hides labels
        // form 1
        s1NightRateLbl.setVisible(false);
        s1FlatRateLbl.setVisible(false);
        s1DayRateLbl.setVisible(false);
        
        
        //initialise values
        //Form 1
        s1KwhPeriod = "";
        s1NightRate = "";
        s1DayRate = "";
        s1FlatRate = "";
        s1Period = "";
        
        s1IncludeVat = false;
        s1IncludeStandingCharge = false;
        s1IncludePsoLevy = false; 
        
        //Form 1: initialises the values, used for parsing inputs to double
        s1DayRateValue = 0.0;
        s1NightRateValue = 0.0;
        s1FlatRateValue = 0.0;
        
        //form 2
        s1EnergySetup = "";
        s1PeopleCount = 1;
        s1NightPercentChoice = "";
        s1NightPercentValue = 0;
        s1PrimaryHeatingChoice = "";
        s1PrimaryHeatingElectric = false;

     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        tabsS1 = new javax.swing.JTabbedPane();
        Form1 = new javax.swing.JPanel();
        s1PeriodLbl = new javax.swing.JLabel();
        s1PeriodCmbox = new javax.swing.JComboBox<>();
        s1KwhPeriodLbl = new javax.swing.JLabel();
        s1KwhPeriodTf = new javax.swing.JTextField();
        s1TariffTypeLbl = new javax.swing.JLabel();
        s1DayNightRateRbtn = new javax.swing.JRadioButton();
        s1FlatRateRbtn = new javax.swing.JRadioButton();
        s1DayRateLbl = new javax.swing.JLabel();
        s1NightRateLbl = new javax.swing.JLabel();
        s1FlatRateLbl = new javax.swing.JLabel();
        s1DayRateTf = new javax.swing.JTextField();
        s1NightRateTf = new javax.swing.JTextField();
        s1FlatRateTf = new javax.swing.JTextField();
        s1UnitRateVatCb = new javax.swing.JCheckBox();
        s1StandingChargeCb = new javax.swing.JCheckBox();
        s1PsoLevyCb = new javax.swing.JCheckBox();
        s1Next1Btn = new javax.swing.JButton();
        Form2 = new javax.swing.JPanel();
        s1HomeEnergySetupLbl = new javax.swing.JLabel();
        s1EnergySetupCmbox = new javax.swing.JComboBox<>();
        s1PeopleInHomeLbl = new javax.swing.JLabel();
        s1PeopleSpn = new javax.swing.JSpinner();
        s1ApproxNightUsageLbl = new javax.swing.JLabel();
        s1NightPercentCmbox = new javax.swing.JComboBox<>();
        s1PrimaryHeatingLbl = new javax.swing.JLabel();
        s1PrimaryHeatingCmbox = new javax.swing.JComboBox<>();
        s1Form2BackBtn = new javax.swing.JButton();
        s1Form2NextBtn = new javax.swing.JButton();
        Results = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        s1TotalPeriodKwhLbl = new javax.swing.JLabel();
        s1TotalPeriodCostLbl = new javax.swing.JLabel();
        s1AnnualKwhLbl = new javax.swing.JLabel();
        s1AnnualCostLbl = new javax.swing.JLabel();
        s1HouseComparisonLbl = new javax.swing.JLabel();
        s1ResKwhPeriodValueLbl = new javax.swing.JLabel();
        s1ResCostPeriodValueLbl = new javax.swing.JLabel();
        s1ResKwhYearValueLbl = new javax.swing.JLabel();
        s1ResCostYearValueLbl = new javax.swing.JLabel();
        s1ResTypCompareValueLbl = new javax.swing.JLabel();
        s1AdviceComparisonScrl = new javax.swing.JScrollPane();
        s1AdviceComparisonTa = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        s1ResultsCardTitleLbl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        s1Done3Btn = new javax.swing.JButton();
        s1ResultsBackBtn = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setLayout(new java.awt.BorderLayout());

        s1PeriodLbl.setText("Period");

        s1PeriodCmbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monthly", "Yearly" }));
        s1PeriodCmbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1PeriodCmboxActionPerformed(evt);
            }
        });

        s1KwhPeriodLbl.setText("kWh for one Month");

        s1KwhPeriodTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1KwhPeriodTfActionPerformed(evt);
            }
        });

        s1TariffTypeLbl.setText("Tariff Type");

        buttonGroup1.add(s1DayNightRateRbtn);
        s1DayNightRateRbtn.setText("Day & Night");
        s1DayNightRateRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1DayNightRateRbtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(s1FlatRateRbtn);
        s1FlatRateRbtn.setText("Flat Rate");
        s1FlatRateRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1FlatRateRbtnActionPerformed(evt);
            }
        });

        s1DayRateLbl.setText("Day Rate (€/kWh)");

        s1NightRateLbl.setText("Night Rate (€/kWh)");

        s1FlatRateLbl.setText("Flat Rate (€/kWh)");

        s1DayRateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1DayRateTfActionPerformed(evt);
            }
        });

        s1NightRateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1NightRateTfActionPerformed(evt);
            }
        });

        s1FlatRateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1FlatRateTfActionPerformed(evt);
            }
        });

        s1UnitRateVatCb.setText("Unit Rate includes VAT");
        s1UnitRateVatCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1UnitRateVatCbActionPerformed(evt);
            }
        });

        s1StandingChargeCb.setText("Include standing charge");
        s1StandingChargeCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1StandingChargeCbActionPerformed(evt);
            }
        });

        s1PsoLevyCb.setText("Include PSO levy");
        s1PsoLevyCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1PsoLevyCbActionPerformed(evt);
            }
        });

        s1Next1Btn.setText("Next");
        s1Next1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1Next1BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Form1Layout = new javax.swing.GroupLayout(Form1);
        Form1.setLayout(Form1Layout);
        Form1Layout.setHorizontalGroup(
            Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Form1Layout.createSequentialGroup()
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Form1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Form1Layout.createSequentialGroup()
                                .addComponent(s1NightRateLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(s1NightRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Form1Layout.createSequentialGroup()
                                .addComponent(s1DayRateLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(s1DayRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Form1Layout.createSequentialGroup()
                                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(Form1Layout.createSequentialGroup()
                                        .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(s1PeriodLbl)
                                            .addComponent(s1TariffTypeLbl))
                                        .addGap(152, 152, 152))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Form1Layout.createSequentialGroup()
                                        .addComponent(s1KwhPeriodLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(Form1Layout.createSequentialGroup()
                                        .addComponent(s1DayNightRateRbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(s1FlatRateRbtn))
                                    .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(s1PeriodCmbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(s1KwhPeriodTf, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(Form1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Form1Layout.createSequentialGroup()
                                .addComponent(s1FlatRateLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(s1FlatRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Form1Layout.createSequentialGroup()
                                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(s1PsoLevyCb, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(s1StandingChargeCb, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(s1UnitRateVatCb, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(s1Next1Btn)))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        Form1Layout.setVerticalGroup(
            Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Form1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1PeriodCmbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1PeriodLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1KwhPeriodTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1KwhPeriodLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1FlatRateRbtn)
                    .addComponent(s1DayNightRateRbtn)
                    .addComponent(s1TariffTypeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s1DayRateLbl)
                    .addComponent(s1DayRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1NightRateLbl)
                    .addComponent(s1NightRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1FlatRateLbl)
                    .addComponent(s1FlatRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(s1UnitRateVatCb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s1StandingChargeCb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1PsoLevyCb)
                    .addComponent(s1Next1Btn))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        tabsS1.addTab("Form 1", Form1);

        s1HomeEnergySetupLbl.setText("Home Energy Setup");

        s1EnergySetupCmbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Solar", "Solar and Inverter", "Solar & Battery" }));
        s1EnergySetupCmbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1EnergySetupCmboxActionPerformed(evt);
            }
        });

        s1PeopleInHomeLbl.setText("People in home");

        s1PeopleSpn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                s1PeopleSpnStateChanged(evt);
            }
        });

        s1ApproxNightUsageLbl.setText("Approx Night Usage");

        s1NightPercentCmbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20%", "30%", "40%", "50%", "60%" }));
        s1NightPercentCmbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1NightPercentCmboxActionPerformed(evt);
            }
        });

        s1PrimaryHeatingLbl.setText("Primary Heating");

        s1PrimaryHeatingCmbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electric", "Gas", "Oil", "Heat Pump", "Solid Fuel" }));
        s1PrimaryHeatingCmbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1PrimaryHeatingCmboxActionPerformed(evt);
            }
        });

        s1Form2BackBtn.setText("Back");
        s1Form2BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1Form2BackBtnActionPerformed(evt);
            }
        });

        s1Form2NextBtn.setText("Next");
        s1Form2NextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1Form2NextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Form2Layout = new javax.swing.GroupLayout(Form2);
        Form2.setLayout(Form2Layout);
        Form2Layout.setHorizontalGroup(
            Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Form2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Form2Layout.createSequentialGroup()
                        .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s1HomeEnergySetupLbl)
                            .addComponent(s1PeopleInHomeLbl))
                        .addGap(18, 18, 18)
                        .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(s1EnergySetupCmbox, 0, 200, Short.MAX_VALUE)
                            .addComponent(s1PeopleSpn)))
                    .addGroup(Form2Layout.createSequentialGroup()
                        .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s1ApproxNightUsageLbl)
                            .addComponent(s1PrimaryHeatingLbl))
                        .addGap(18, 18, 18)
                        .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s1NightPercentCmbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(s1PrimaryHeatingCmbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(Form2Layout.createSequentialGroup()
                        .addComponent(s1Form2BackBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(s1Form2NextBtn)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        Form2Layout.setVerticalGroup(
            Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Form2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s1EnergySetupCmbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1HomeEnergySetupLbl))
                .addGap(18, 18, 18)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s1PeopleInHomeLbl)
                    .addComponent(s1PeopleSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s1ApproxNightUsageLbl)
                    .addComponent(s1NightPercentCmbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s1PrimaryHeatingCmbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1PrimaryHeatingLbl))
                .addGap(35, 35, 35)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1Form2BackBtn)
                    .addComponent(s1Form2NextBtn))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        tabsS1.addTab("Form 2", Form2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Your Results"));

        s1TotalPeriodKwhLbl.setText("Total kWh (period): ");

        s1TotalPeriodCostLbl.setText("Total cost (period):");

        s1AnnualKwhLbl.setText("Annual kWh:");

        s1AnnualCostLbl.setText("Annual Cost");

        s1HouseComparisonLbl.setText("Typical household comparison:");

        s1ResKwhPeriodValueLbl.setText("\"\"");

        s1ResCostPeriodValueLbl.setText("\"\"");

        s1ResKwhYearValueLbl.setText("\"\"");

        s1ResCostYearValueLbl.setText("\"\"");

        s1ResTypCompareValueLbl.setText("\"\"");

        s1AdviceComparisonTa.setColumns(20);
        s1AdviceComparisonTa.setRows(5);
        s1AdviceComparisonTa.setText("Advice and comparison to \na typical Irish household \nwill be display here.");
        s1AdviceComparisonScrl.setViewportView(s1AdviceComparisonTa);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s1AdviceComparisonScrl, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(s1TotalPeriodCostLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(s1AnnualKwhLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(s1AnnualCostLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(s1HouseComparisonLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(s1TotalPeriodKwhLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s1ResKwhPeriodValueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s1ResCostPeriodValueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s1ResKwhYearValueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s1ResTypCompareValueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s1ResCostYearValueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1TotalPeriodKwhLbl)
                    .addComponent(s1ResKwhPeriodValueLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1ResCostPeriodValueLbl)
                    .addComponent(s1TotalPeriodCostLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1ResKwhYearValueLbl)
                    .addComponent(s1AnnualKwhLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1ResCostYearValueLbl)
                    .addComponent(s1AnnualCostLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s1ResTypCompareValueLbl)
                    .addComponent(s1HouseComparisonLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s1AdviceComparisonScrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Card"));

        s1ResultsCardTitleLbl.setText("Card Title");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(s1ResultsCardTitleLbl)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(s1ResultsCardTitleLbl)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Image Placeholder"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        s1Done3Btn.setText("Done");
        s1Done3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1Done3BtnActionPerformed(evt);
            }
        });

        s1ResultsBackBtn.setText("Back");
        s1ResultsBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ResultsBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResultsLayout = new javax.swing.GroupLayout(Results);
        Results.setLayout(ResultsLayout);
        ResultsLayout.setHorizontalGroup(
            ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultsLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultsLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(s1ResultsBackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(s1Done3Btn)
                .addGap(87, 87, 87))
        );
        ResultsLayout.setVerticalGroup(
            ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1Done3Btn)
                    .addComponent(s1ResultsBackBtn))
                .addGap(0, 55, Short.MAX_VALUE))
        );

        tabsS1.addTab("Results", Results);

        add(tabsS1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void s1PeriodCmboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1PeriodCmboxActionPerformed
        // TODO add your handling code here:
        String period = s1PeriodCmbox.getSelectedItem().toString();
        // if the monthly option is selected
        if (period.equals("Monthly")){
            s1KwhPeriodLbl.setText("kWh for one Month");//updates the label text below period options
            s1KwhPeriodTf.setToolTipText("Enter kWh used in one Month");//when user hover over Monthly option text field, this info is displayed
        }else{ //else use this for Yearly selection
            s1KwhPeriodLbl.setText("kWh for one Year");//updates the label text below period options
            s1KwhPeriodTf.setToolTipText("Enter kWh used in one year");//when user hover over Yearly option text field, this info is displayed
        }
    }//GEN-LAST:event_s1PeriodCmboxActionPerformed

    private void s1FlatRateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1FlatRateTfActionPerformed
        // TODO add your handling code here:
        s1FlatRate = s1FlatRateTf.getText();
    }//GEN-LAST:event_s1FlatRateTfActionPerformed

    private void s1Next1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1Next1BtnActionPerformed
        //captures either selected monthly or yearly option, converts to string
        s1Period = s1PeriodCmbox.getSelectedItem().toString(); 
        // captures kwh text from field
        s1KwhPeriod = s1KwhPeriodTf.getText().strip();
        //captures the tariff type day or night rate
        boolean isDayNight = s1DayNightRateRbtn.isSelected();
        //captures tariff rate flat rate
        boolean isFlat = s1FlatRateRbtn.isSelected();
        //text taken from input fields and stored in variables
        s1DayRate = s1DayRateTf.getText().strip();
        s1NightRate = s1NightRateTf.getText().strip();
        s1FlatRate = s1FlatRateTf.getText().strip();
        //user selected cb options stored here 
        s1IncludeVat = s1UnitRateVatCb.isSelected();
        s1IncludeStandingCharge = s1StandingChargeCb.isSelected();
        s1IncludePsoLevy = s1PsoLevyCb.isSelected();
        //validation for empty input kWh field
        if(s1KwhPeriod.equals("")){
            JOptionPane.showMessageDialog(null,"Please enter kWh for the selected period");
            return;
        }
        //validation when neither option for Day & Night or Flat Rate is selected
        if(!isDayNight && !isFlat){
            JOptionPane.showMessageDialog(null,"Please select Day & Night or Flat Rate");
            return;
        }
        
        try{
            s1KwhPeriodValue = Double.parseDouble(s1KwhPeriod); //parses s1KwhPeriod and then stores the value as a double in s1KwhPeriodValue
            if (s1KwhPeriodValue <= 0) {
                JOptionPane.showMessageDialog(null,"Kwh must be greater than 0");
                return;
            }
        } catch(NumberFormatException e){ 
            JOptionPane.showMessageDialog(null,"kWh must be a number");
            return;
        }
        //validation for Day & Night rate input fields
        if (isDayNight) {
            if (s1DayRate.equals("") || s1NightRate.equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter both Day Rate and also Night Rate");
                return;
            }
            try {
                s1DayRateValue = Double.parseDouble(s1DayRate);
                s1NightRateValue = Double.parseDouble(s1NightRate);
                if (s1DayRateValue <0 || s1NightRateValue <0){
                    JOptionPane.showMessageDialog(null,"Must not be a negative number. Please input more than 0");
                    return;
                }
            }catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(null,"Day Rate and also Night Rate must be a valid number");
                return;
            }
        }
        //validation for flat rate input field
        if (isFlat){
            if (s1FlatRate.equals("")){
                JOptionPane.showMessageDialog(null,"Please enter the Flat Rate");
                return;
            }
            try{
                s1FlatRateValue = Double.parseDouble(s1FlatRate);
                if (s1FlatRateValue <0) {
                    JOptionPane.showMessageDialog(null,"The Flat Rate cannot be a negative number");
                    return;
                }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Flat Rate must be a valid number");
                return;
            }
        }
        // moves to next form (form 2)
        tabsS1.setSelectedIndex(1);
        
        
    }//GEN-LAST:event_s1Next1BtnActionPerformed

    private void s1Form2BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1Form2BackBtnActionPerformed
        tabsS1.setSelectedIndex(0);
    }//GEN-LAST:event_s1Form2BackBtnActionPerformed

    private void s1Form2NextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1Form2NextBtnActionPerformed
    //capture the form 2 values when clicked
        //captures energy set up selection
        s1EnergySetup = s1EnergySetupCmbox.getSelectedItem().toString();
        //capture the spinner value
        s1PeopleCount = (int) s1PeopleSpn.getValue();
        //captures the night percentage selection
        s1NightPercentChoice = s1NightPercentCmbox.getSelectedItem().toString();
        // captures the primary heating selection
        s1PrimaryHeatingChoice = s1PrimaryHeatingCmbox.getSelectedItem().toString();
        
        //when button clicked this gets the true,false value for primary heating choice
        // if Electric is picked, then sets to true , else its false
        s1PrimaryHeatingElectric = s1PrimaryHeatingChoice.equals("Electric");
        
        //validation for no. of people, has to be greater than 0
        if (s1PeopleCount <= 0) {
            JOptionPane.showMessageDialog(null, "Number of people must be at least 1"); 
            return;
        }
        //moves to results tab
        tabsS1.setSelectedIndex(2);
    }//GEN-LAST:event_s1Form2NextBtnActionPerformed

    private void s1ResultsBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ResultsBackBtnActionPerformed
        tabsS1.setSelectedIndex(1);
    }//GEN-LAST:event_s1ResultsBackBtnActionPerformed

    private void s1Done3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1Done3BtnActionPerformed
        ui.MainFrame mf = (ui.MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        mf.goLanding();
    }//GEN-LAST:event_s1Done3BtnActionPerformed

    private void s1KwhPeriodTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1KwhPeriodTfActionPerformed
        // TODO add your handling code here:
        s1KwhPeriod = s1KwhPeriodTf.getText();//captures the text from field and stored in variable
        
    }//GEN-LAST:event_s1KwhPeriodTfActionPerformed

    private void s1PrimaryHeatingCmboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1PrimaryHeatingCmboxActionPerformed
        // TODO add your handling code here:
        s1PrimaryHeatingChoice = s1PrimaryHeatingCmbox.getSelectedItem().toString();
        s1PrimaryHeatingElectric = s1PrimaryHeatingChoice.equals("Electric");
    }//GEN-LAST:event_s1PrimaryHeatingCmboxActionPerformed

    private void s1UnitRateVatCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1UnitRateVatCbActionPerformed
        // TODO add your handling code here:
        s1IncludeVat = s1UnitRateVatCb.isSelected();
        
    }//GEN-LAST:event_s1UnitRateVatCbActionPerformed

    private void s1DayNightRateRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1DayNightRateRbtnActionPerformed
        // TODO add your handling code here:
        if (s1DayNightRateRbtn.isSelected()){
        s1DayRateTf.setVisible(true); //show the day rate text field 
        s1DayRateLbl.setVisible(true); //show the day rate label 
        s1NightRateTf.setVisible(true);//show the night rate text field 
        s1NightRateLbl.setVisible(true);//show the night rate label 
        
  
        s1FlatRateTf.setVisible(false);// keep flat rate text field hidden
        s1FlatRateTf.setText(""); //clears the flat rate text when hidden
        s1FlatRateLbl.setVisible(false);// keep flat rate label hidden
        
        s1UnitRateVatCb.setVisible(true); //shows the VAT cb
        s1StandingChargeCb.setVisible(true); //shows the standing charge cb
        s1PsoLevyCb.setVisible(true);// show PSO cb
        }
        
    }//GEN-LAST:event_s1DayNightRateRbtnActionPerformed

    private void s1FlatRateRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1FlatRateRbtnActionPerformed
        // TODO add your handling code here:
        if (s1FlatRateRbtn.isSelected()){
        s1DayRateTf.setVisible(false); //hides the day rate text field 
        s1DayRateLbl.setVisible(false); //hide the day rate label 
        s1NightRateTf.setVisible(false);//hides the night rate text field 
        s1DayRateTf.setText(""); //clears the day rate text when hidden
        s1NightRateTf.setText("");  //clears the night text rate when hidden 
        s1NightRateLbl.setVisible(false);//hide the night rate label
        
        s1FlatRateTf.setVisible(true);// shows flat rate text field 
        s1FlatRateLbl.setVisible(true);// shows flat rate label
        
        s1UnitRateVatCb.setVisible(true); //shows the VAT cb
        s1StandingChargeCb.setVisible(true); //shows the standing charge cb
        s1PsoLevyCb.setVisible(true);// show PSO cb
        }
        
    }//GEN-LAST:event_s1FlatRateRbtnActionPerformed

    private void s1NightRateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1NightRateTfActionPerformed
        // TODO add your handling code here:
        s1NightRate = s1NightRateTf.getText();
    }//GEN-LAST:event_s1NightRateTfActionPerformed

    private void s1DayRateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1DayRateTfActionPerformed
        // TODO add your handling code here:
        s1DayRate = s1DayRateTf.getText();
    }//GEN-LAST:event_s1DayRateTfActionPerformed

    private void s1StandingChargeCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1StandingChargeCbActionPerformed
        // TODO add your handling code here:
        s1IncludeStandingCharge = s1StandingChargeCb.isSelected();
    }//GEN-LAST:event_s1StandingChargeCbActionPerformed

    private void s1PsoLevyCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1PsoLevyCbActionPerformed
        // TODO add your handling code here:
        s1IncludePsoLevy = s1PsoLevyCb.isSelected();
    }//GEN-LAST:event_s1PsoLevyCbActionPerformed

    private void s1EnergySetupCmboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1EnergySetupCmboxActionPerformed
        // TODO add your handling code here:
        //capture selection for energy setup
        s1EnergySetup = s1EnergySetupCmbox.getSelectedItem().toString();
        
    }//GEN-LAST:event_s1EnergySetupCmboxActionPerformed

    private void s1PeopleSpnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_s1PeopleSpnStateChanged
        // TODO add your handling code here:
        s1PeopleCount = (int) s1PeopleSpn.getValue(); //captures the spinners value as an integer
    }//GEN-LAST:event_s1PeopleSpnStateChanged

    private void s1NightPercentCmboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1NightPercentCmboxActionPerformed
        // TODO add your handling code here:
        s1NightPercentChoice = s1NightPercentCmbox.getSelectedItem().toString();
    }//GEN-LAST:event_s1NightPercentCmboxActionPerformed

    public void goForm1() {
        tabsS1.setSelectedIndex(0);
    }

    public void goForm2() {
        tabsS1.setSelectedIndex(1);
    }

    public void goResults() {
        tabsS1.setSelectedIndex(2);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Form1;
    private javax.swing.JPanel Form2;
    private javax.swing.JPanel Results;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane s1AdviceComparisonScrl;
    private javax.swing.JTextArea s1AdviceComparisonTa;
    private javax.swing.JLabel s1AnnualCostLbl;
    private javax.swing.JLabel s1AnnualKwhLbl;
    private javax.swing.JLabel s1ApproxNightUsageLbl;
    private javax.swing.JRadioButton s1DayNightRateRbtn;
    private javax.swing.JLabel s1DayRateLbl;
    private javax.swing.JTextField s1DayRateTf;
    private javax.swing.JButton s1Done3Btn;
    private javax.swing.JComboBox<String> s1EnergySetupCmbox;
    private javax.swing.JLabel s1FlatRateLbl;
    private javax.swing.JRadioButton s1FlatRateRbtn;
    private javax.swing.JTextField s1FlatRateTf;
    private javax.swing.JButton s1Form2BackBtn;
    private javax.swing.JButton s1Form2NextBtn;
    private javax.swing.JLabel s1HomeEnergySetupLbl;
    private javax.swing.JLabel s1HouseComparisonLbl;
    private javax.swing.JLabel s1KwhPeriodLbl;
    private javax.swing.JTextField s1KwhPeriodTf;
    private javax.swing.JButton s1Next1Btn;
    private javax.swing.JComboBox<String> s1NightPercentCmbox;
    private javax.swing.JLabel s1NightRateLbl;
    private javax.swing.JTextField s1NightRateTf;
    private javax.swing.JLabel s1PeopleInHomeLbl;
    private javax.swing.JSpinner s1PeopleSpn;
    private javax.swing.JComboBox<String> s1PeriodCmbox;
    private javax.swing.JLabel s1PeriodLbl;
    private javax.swing.JComboBox<String> s1PrimaryHeatingCmbox;
    private javax.swing.JLabel s1PrimaryHeatingLbl;
    private javax.swing.JCheckBox s1PsoLevyCb;
    private javax.swing.JLabel s1ResCostPeriodValueLbl;
    private javax.swing.JLabel s1ResCostYearValueLbl;
    private javax.swing.JLabel s1ResKwhPeriodValueLbl;
    private javax.swing.JLabel s1ResKwhYearValueLbl;
    private javax.swing.JLabel s1ResTypCompareValueLbl;
    private javax.swing.JButton s1ResultsBackBtn;
    private javax.swing.JLabel s1ResultsCardTitleLbl;
    private javax.swing.JCheckBox s1StandingChargeCb;
    private javax.swing.JLabel s1TariffTypeLbl;
    private javax.swing.JLabel s1TotalPeriodCostLbl;
    private javax.swing.JLabel s1TotalPeriodKwhLbl;
    private javax.swing.JCheckBox s1UnitRateVatCb;
    private javax.swing.JTabbedPane tabsS1;
    // End of variables declaration//GEN-END:variables
}
