/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.section1;

/**
 *
 * @author jamesmurphy
 */
public class Section1Panel extends javax.swing.JPanel {

    /**
     * Creates new form Section1Panel
     */
    public Section1Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        tabsS1 = new javax.swing.JTabbedPane();
        Form1 = new javax.swing.JPanel();
        s1PeriodLbl = new javax.swing.JLabel();
        s1PeriodCb = new javax.swing.JComboBox<>();
        s1KwhPeriodLbl = new javax.swing.JLabel();
        s1KwhPeriodTf = new javax.swing.JTextField();
        s1TariffTypeLbl = new javax.swing.JLabel();
        s1DayNightRateRbtn = new javax.swing.JRadioButton();
        s1FlatRateRbtn = new javax.swing.JRadioButton();
        s1DayRateLbl = new javax.swing.JLabel();
        s1NightRateLbl = new javax.swing.JLabel();
        s1FlatRateLbl = new javax.swing.JLabel();
        DayRateTf = new javax.swing.JTextField();
        NightRateTf = new javax.swing.JTextField();
        s1FlatRateTf = new javax.swing.JTextField();
        s1UnitRateVatCb = new javax.swing.JCheckBox();
        s1StandingChargeCb = new javax.swing.JCheckBox();
        s1PsoLevyCb = new javax.swing.JCheckBox();
        s1Next1Btn = new javax.swing.JButton();
        Form2 = new javax.swing.JPanel();
        s1HomeEnergySetupLbl = new javax.swing.JLabel();
        s1EnergySetupCb = new javax.swing.JComboBox<>();
        s1PeopleInHomeLbl = new javax.swing.JLabel();
        s1PeopleSpn = new javax.swing.JSpinner();
        s1ApproxNightUsageLbl = new javax.swing.JLabel();
        s1NightPercentCb = new javax.swing.JComboBox<>();
        s1PrimaryHeatingLbl = new javax.swing.JLabel();
        s1PrimaryHeatingCb = new javax.swing.JComboBox<>();
        s1Form2BackBtn = new javax.swing.JButton();
        s1Form2NextBtn = new javax.swing.JButton();
        Results = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        s1TotalPeriodKwhLbl = new javax.swing.JLabel();
        s1TotalPeriodCostLbl = new javax.swing.JLabel();
        s1AnnualKwhLbl = new javax.swing.JLabel();
        s1AnnualCostLbl = new javax.swing.JLabel();
        s1HouseComparisonLbl = new javax.swing.JLabel();
        s1ResKwhPeriodValueLbl = new javax.swing.JLabel();
        s1ResCostPeriodValueLbl = new javax.swing.JLabel();
        s1ResKwhYearValueLbl = new javax.swing.JLabel();
        s1ResCostYearValueLbl = new javax.swing.JLabel();
        s1ResTypCompareValueLbl = new javax.swing.JLabel();
        s1AdviceComparisonScrl = new javax.swing.JScrollPane();
        s1AdviceComparisonTa = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        s1ResultsCardTitleLbl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        s1Done3Btn = new javax.swing.JButton();
        s1ResultsBackBtn = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setLayout(new java.awt.BorderLayout());

        s1PeriodLbl.setText("Period");

        s1PeriodCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monthly", "Yearly" }));
        s1PeriodCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1PeriodCbActionPerformed(evt);
            }
        });

        s1KwhPeriodLbl.setText("kWh for period");

        s1KwhPeriodTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1KwhPeriodTfActionPerformed(evt);
            }
        });

        s1TariffTypeLbl.setText("Tariff Type");

        buttonGroup1.add(s1DayNightRateRbtn);
        s1DayNightRateRbtn.setText("Day & Night");

        buttonGroup1.add(s1FlatRateRbtn);
        s1FlatRateRbtn.setText("Flat Rate");

        s1DayRateLbl.setText("Day Rate (€/kWh)");

        s1NightRateLbl.setText("Night Rate (€/kWh)");

        s1FlatRateLbl.setText("Flat Rate (€/kWh)");

        s1FlatRateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1FlatRateTfActionPerformed(evt);
            }
        });

        s1UnitRateVatCb.setText("Unit Rate includes VAT");

        s1StandingChargeCb.setText("Include standing charge");

        s1PsoLevyCb.setText("Include PSO levy");

        s1Next1Btn.setText("Next");
        s1Next1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1Next1BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Form1Layout = new javax.swing.GroupLayout(Form1);
        Form1.setLayout(Form1Layout);
        Form1Layout.setHorizontalGroup(
            Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Form1Layout.createSequentialGroup()
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Form1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Form1Layout.createSequentialGroup()
                                .addComponent(s1NightRateLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(s1FlatRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Form1Layout.createSequentialGroup()
                                .addComponent(s1DayRateLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DayRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Form1Layout.createSequentialGroup()
                                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(s1PeriodLbl)
                                    .addComponent(s1KwhPeriodLbl)
                                    .addComponent(s1TariffTypeLbl))
                                .addGap(104, 104, 104)
                                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(Form1Layout.createSequentialGroup()
                                        .addComponent(s1DayNightRateRbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(s1FlatRateRbtn))
                                    .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(s1PeriodCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(s1KwhPeriodTf, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Form1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Form1Layout.createSequentialGroup()
                                .addComponent(s1PsoLevyCb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(s1Next1Btn))
                            .addComponent(s1StandingChargeCb, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s1UnitRateVatCb, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Form1Layout.createSequentialGroup()
                                .addComponent(s1FlatRateLbl)
                                .addGap(91, 91, 91)
                                .addComponent(NightRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(142, 142, 142)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        Form1Layout.setVerticalGroup(
            Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Form1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1PeriodCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1PeriodLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s1KwhPeriodLbl)
                    .addComponent(s1KwhPeriodTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1FlatRateRbtn)
                    .addComponent(s1DayNightRateRbtn)
                    .addComponent(s1TariffTypeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s1DayRateLbl)
                    .addComponent(DayRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s1NightRateLbl)
                    .addComponent(s1FlatRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NightRateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1FlatRateLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Form1Layout.createSequentialGroup()
                        .addComponent(s1UnitRateVatCb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s1StandingChargeCb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(s1PsoLevyCb))
                    .addComponent(s1Next1Btn))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tabsS1.addTab("Form 1", Form1);

        s1HomeEnergySetupLbl.setText("Home Energy Setup");

        s1EnergySetupCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Solar", "Solar and Inverter", "Solar & Battery" }));

        s1PeopleInHomeLbl.setText("People in home");

        s1ApproxNightUsageLbl.setText("Approx Night Usage");

        s1NightPercentCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20%", "30%", "40%", "50%", "60%" }));

        s1PrimaryHeatingLbl.setText("Primary Heating");

        s1PrimaryHeatingCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electric", "Gas", "Oil", "Heat Pump", "Solid Fuel" }));
        s1PrimaryHeatingCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1PrimaryHeatingCbActionPerformed(evt);
            }
        });

        s1Form2BackBtn.setText("Back");
        s1Form2BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1Form2BackBtnActionPerformed(evt);
            }
        });

        s1Form2NextBtn.setText("Next");
        s1Form2NextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1Form2NextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Form2Layout = new javax.swing.GroupLayout(Form2);
        Form2.setLayout(Form2Layout);
        Form2Layout.setHorizontalGroup(
            Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Form2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Form2Layout.createSequentialGroup()
                        .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s1HomeEnergySetupLbl)
                            .addComponent(s1PeopleInHomeLbl))
                        .addGap(18, 18, 18)
                        .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(s1EnergySetupCb, 0, 200, Short.MAX_VALUE)
                            .addComponent(s1PeopleSpn)))
                    .addGroup(Form2Layout.createSequentialGroup()
                        .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s1ApproxNightUsageLbl)
                            .addComponent(s1PrimaryHeatingLbl))
                        .addGap(18, 18, 18)
                        .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s1NightPercentCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(s1PrimaryHeatingCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(Form2Layout.createSequentialGroup()
                        .addComponent(s1Form2BackBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(s1Form2NextBtn)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        Form2Layout.setVerticalGroup(
            Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Form2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s1EnergySetupCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1HomeEnergySetupLbl))
                .addGap(18, 18, 18)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s1PeopleInHomeLbl)
                    .addComponent(s1PeopleSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s1ApproxNightUsageLbl)
                    .addComponent(s1NightPercentCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s1PrimaryHeatingCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1PrimaryHeatingLbl))
                .addGap(35, 35, 35)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1Form2BackBtn)
                    .addComponent(s1Form2NextBtn))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        tabsS1.addTab("Form 2", Form2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Your Results"));

        s1TotalPeriodKwhLbl.setText("Total kWh (period): ");

        s1TotalPeriodCostLbl.setText("Total cost (period):");

        s1AnnualKwhLbl.setText("Annual kWh:");

        s1AnnualCostLbl.setText("Annual Cost");

        s1HouseComparisonLbl.setText("Typical household comparison:");

        s1ResKwhPeriodValueLbl.setText("\"\"");

        s1ResCostPeriodValueLbl.setText("\"\"");

        s1ResKwhYearValueLbl.setText("\"\"");

        s1ResCostYearValueLbl.setText("\"\"");

        s1ResTypCompareValueLbl.setText("\"\"");

        s1AdviceComparisonTa.setColumns(20);
        s1AdviceComparisonTa.setRows(5);
        s1AdviceComparisonTa.setText("Advice and comparison to \na typical Irish household \nwill be display here.");
        s1AdviceComparisonScrl.setViewportView(s1AdviceComparisonTa);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s1AdviceComparisonScrl, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(s1TotalPeriodCostLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(s1AnnualKwhLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(s1AnnualCostLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(s1HouseComparisonLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(s1TotalPeriodKwhLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s1ResKwhPeriodValueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s1ResCostPeriodValueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s1ResKwhYearValueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s1ResTypCompareValueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s1ResCostYearValueLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1TotalPeriodKwhLbl)
                    .addComponent(s1ResKwhPeriodValueLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1ResCostPeriodValueLbl)
                    .addComponent(s1TotalPeriodCostLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1ResKwhYearValueLbl)
                    .addComponent(s1AnnualKwhLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1ResCostYearValueLbl)
                    .addComponent(s1AnnualCostLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s1ResTypCompareValueLbl)
                    .addComponent(s1HouseComparisonLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s1AdviceComparisonScrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Card"));

        s1ResultsCardTitleLbl.setText("Card Title");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(s1ResultsCardTitleLbl)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(s1ResultsCardTitleLbl)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Image Placeholder"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        s1Done3Btn.setText("Done");
        s1Done3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1Done3BtnActionPerformed(evt);
            }
        });

        s1ResultsBackBtn.setText("Back");
        s1ResultsBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ResultsBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResultsLayout = new javax.swing.GroupLayout(Results);
        Results.setLayout(ResultsLayout);
        ResultsLayout.setHorizontalGroup(
            ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultsLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultsLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(s1ResultsBackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(s1Done3Btn)
                .addGap(87, 87, 87))
        );
        ResultsLayout.setVerticalGroup(
            ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s1Done3Btn)
                    .addComponent(s1ResultsBackBtn))
                .addGap(0, 48, Short.MAX_VALUE))
        );

        tabsS1.addTab("Results", Results);

        add(tabsS1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void s1PeriodCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1PeriodCbActionPerformed
        // TODO add your handling code here:
        String period = s1PeriodCb.getSelectedItem().toString();
        // if the monthly option is selected
        if (period.equals("Monthly")){
            s1KwhPeriodLbl.setText("Enter kWh used in one Month");//updates the label text below period options
            s1KwhPeriodTf.setToolTipText("Enter kWh used in one Month");//when user hover over Monthly option, this info is displayed
        }else{ //else use this for Yearly selection
            s1KwhPeriodLbl.setText("Enter kWh used in one Year");//updates the label text below period options
            s1KwhPeriodTf.setToolTipText("Enter kWh used in one year");//when user hover over Yearly option, this info is displayed
        }
    }//GEN-LAST:event_s1PeriodCbActionPerformed

    private void s1FlatRateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1FlatRateTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1FlatRateTfActionPerformed

    private void s1Next1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1Next1BtnActionPerformed
        tabsS1.setSelectedIndex(1);
    }//GEN-LAST:event_s1Next1BtnActionPerformed

    private void s1Form2BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1Form2BackBtnActionPerformed
        tabsS1.setSelectedIndex(0);
    }//GEN-LAST:event_s1Form2BackBtnActionPerformed

    private void s1Form2NextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1Form2NextBtnActionPerformed
        tabsS1.setSelectedIndex(2);
    }//GEN-LAST:event_s1Form2NextBtnActionPerformed

    private void s1ResultsBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ResultsBackBtnActionPerformed
        tabsS1.setSelectedIndex(1);
    }//GEN-LAST:event_s1ResultsBackBtnActionPerformed

    private void s1Done3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1Done3BtnActionPerformed
        ui.MainFrame mf = (ui.MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        mf.goLanding();
    }//GEN-LAST:event_s1Done3BtnActionPerformed

    private void s1KwhPeriodTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1KwhPeriodTfActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_s1KwhPeriodTfActionPerformed

    private void s1PrimaryHeatingCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1PrimaryHeatingCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1PrimaryHeatingCbActionPerformed

    public void goForm1() {
        tabsS1.setSelectedIndex(0);
    }

    public void goForm2() {
        tabsS1.setSelectedIndex(1);
    }

    public void goResults() {
        tabsS1.setSelectedIndex(2);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DayRateTf;
    private javax.swing.JPanel Form1;
    private javax.swing.JPanel Form2;
    private javax.swing.JTextField NightRateTf;
    private javax.swing.JPanel Results;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane s1AdviceComparisonScrl;
    private javax.swing.JTextArea s1AdviceComparisonTa;
    private javax.swing.JLabel s1AnnualCostLbl;
    private javax.swing.JLabel s1AnnualKwhLbl;
    private javax.swing.JLabel s1ApproxNightUsageLbl;
    private javax.swing.JRadioButton s1DayNightRateRbtn;
    private javax.swing.JLabel s1DayRateLbl;
    private javax.swing.JButton s1Done3Btn;
    private javax.swing.JComboBox<String> s1EnergySetupCb;
    private javax.swing.JLabel s1FlatRateLbl;
    private javax.swing.JRadioButton s1FlatRateRbtn;
    private javax.swing.JTextField s1FlatRateTf;
    private javax.swing.JButton s1Form2BackBtn;
    private javax.swing.JButton s1Form2NextBtn;
    private javax.swing.JLabel s1HomeEnergySetupLbl;
    private javax.swing.JLabel s1HouseComparisonLbl;
    private javax.swing.JLabel s1KwhPeriodLbl;
    private javax.swing.JTextField s1KwhPeriodTf;
    private javax.swing.JButton s1Next1Btn;
    private javax.swing.JComboBox<String> s1NightPercentCb;
    private javax.swing.JLabel s1NightRateLbl;
    private javax.swing.JLabel s1PeopleInHomeLbl;
    private javax.swing.JSpinner s1PeopleSpn;
    private javax.swing.JComboBox<String> s1PeriodCb;
    private javax.swing.JLabel s1PeriodLbl;
    private javax.swing.JComboBox<String> s1PrimaryHeatingCb;
    private javax.swing.JLabel s1PrimaryHeatingLbl;
    private javax.swing.JCheckBox s1PsoLevyCb;
    private javax.swing.JLabel s1ResCostPeriodValueLbl;
    private javax.swing.JLabel s1ResCostYearValueLbl;
    private javax.swing.JLabel s1ResKwhPeriodValueLbl;
    private javax.swing.JLabel s1ResKwhYearValueLbl;
    private javax.swing.JLabel s1ResTypCompareValueLbl;
    private javax.swing.JButton s1ResultsBackBtn;
    private javax.swing.JLabel s1ResultsCardTitleLbl;
    private javax.swing.JCheckBox s1StandingChargeCb;
    private javax.swing.JLabel s1TariffTypeLbl;
    private javax.swing.JLabel s1TotalPeriodCostLbl;
    private javax.swing.JLabel s1TotalPeriodKwhLbl;
    private javax.swing.JCheckBox s1UnitRateVatCb;
    private javax.swing.JTabbedPane tabsS1;
    // End of variables declaration//GEN-END:variables
}
