/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.section2;

/**
 *
 * @author jamesmurphy
 */
public class Section2Panel extends javax.swing.JPanel {

    /**
     * Creates new form Section2Panel
     */
    public Section2Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpS2Presets = new javax.swing.ButtonGroup();
        contentPanelSection2 = new javax.swing.JPanel();
        Section2TitleContainer = new javax.swing.JPanel();
        titleSection2 = new javax.swing.JLabel();
        adjustUsageSliderContainer = new javax.swing.JPanel();
        presetsSection2PanelContainer = new javax.swing.JPanel();
        presetsLabelSection2Panel = new javax.swing.JLabel();
        rdoS2PresetWinter = new javax.swing.JRadioButton();
        rdoS2PresetSummer = new javax.swing.JRadioButton();
        rdoS2PresetNewAppliance = new javax.swing.JRadioButton();
        resultsSection2PanelContainer = new javax.swing.JPanel();
        annualCostResultsContainer = new javax.swing.JPanel();
        differenceCostLabel = new javax.swing.JLabel();
        chartCostSection2Panel = new javax.swing.JPanel();
        co2ImpactResultsContainer = new javax.swing.JPanel();
        differenceImpactLabel = new javax.swing.JLabel();
        chartImpactSection2Panel = new javax.swing.JPanel();
        btnContainerSection2Panel = new javax.swing.JPanel();
        btnS2Back = new javax.swing.JButton();
        btnS2Next = new javax.swing.JButton();
        sldS2UsagePercent = new javax.swing.JSlider();
        adjustUsageLabel = new javax.swing.JLabel();

        contentPanelSection2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titleSection2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        titleSection2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleSection2.setText("Usage Slider");

        javax.swing.GroupLayout Section2TitleContainerLayout = new javax.swing.GroupLayout(Section2TitleContainer);
        Section2TitleContainer.setLayout(Section2TitleContainerLayout);
        Section2TitleContainerLayout.setHorizontalGroup(
            Section2TitleContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Section2TitleContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleSection2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
        );
        Section2TitleContainerLayout.setVerticalGroup(
            Section2TitleContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Section2TitleContainerLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(titleSection2))
        );

        adjustUsageSliderContainer.setLayout(new java.awt.BorderLayout(30, 0));

        presetsLabelSection2Panel.setText("Presets:");
        presetsLabelSection2Panel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        grpS2Presets.add(rdoS2PresetWinter);
        rdoS2PresetWinter.setText("Winter");
        rdoS2PresetWinter.setBorder(null);
        rdoS2PresetWinter.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rdoS2PresetWinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoS2PresetWinterActionPerformed(evt);
            }
        });

        grpS2Presets.add(rdoS2PresetSummer);
        rdoS2PresetSummer.setText("Summer");
        rdoS2PresetSummer.setBorder(null);
        rdoS2PresetSummer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        grpS2Presets.add(rdoS2PresetNewAppliance);
        rdoS2PresetNewAppliance.setText("New Appliance");
        rdoS2PresetNewAppliance.setBorder(null);
        rdoS2PresetNewAppliance.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout presetsSection2PanelContainerLayout = new javax.swing.GroupLayout(presetsSection2PanelContainer);
        presetsSection2PanelContainer.setLayout(presetsSection2PanelContainerLayout);
        presetsSection2PanelContainerLayout.setHorizontalGroup(
            presetsSection2PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(presetsSection2PanelContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(presetsLabelSection2Panel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoS2PresetWinter)
                .addGap(36, 36, 36)
                .addComponent(rdoS2PresetSummer)
                .addGap(18, 18, 18)
                .addComponent(rdoS2PresetNewAppliance)
                .addContainerGap())
        );
        presetsSection2PanelContainerLayout.setVerticalGroup(
            presetsSection2PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(presetsSection2PanelContainerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(presetsSection2PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoS2PresetNewAppliance, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoS2PresetSummer)
                    .addComponent(rdoS2PresetWinter, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(presetsLabelSection2Panel))
                .addGap(19, 19, 19))
        );

        resultsSection2PanelContainer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Results", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 13))); // NOI18N
        resultsSection2PanelContainer.setLayout(new java.awt.GridLayout());

        annualCostResultsContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Annual Cost: €"));

        differenceCostLabel.setText("Difference:");

        chartCostSection2Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Chart"));

        javax.swing.GroupLayout chartCostSection2PanelLayout = new javax.swing.GroupLayout(chartCostSection2Panel);
        chartCostSection2Panel.setLayout(chartCostSection2PanelLayout);
        chartCostSection2PanelLayout.setHorizontalGroup(
            chartCostSection2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chartCostSection2PanelLayout.setVerticalGroup(
            chartCostSection2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout annualCostResultsContainerLayout = new javax.swing.GroupLayout(annualCostResultsContainer);
        annualCostResultsContainer.setLayout(annualCostResultsContainerLayout);
        annualCostResultsContainerLayout.setHorizontalGroup(
            annualCostResultsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annualCostResultsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(annualCostResultsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(annualCostResultsContainerLayout.createSequentialGroup()
                        .addComponent(differenceCostLabel)
                        .addGap(0, 232, Short.MAX_VALUE))
                    .addComponent(chartCostSection2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        annualCostResultsContainerLayout.setVerticalGroup(
            annualCostResultsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annualCostResultsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(differenceCostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chartCostSection2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        resultsSection2PanelContainer.add(annualCostResultsContainer);

        co2ImpactResultsContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Co2 impact: kg"));

        differenceImpactLabel.setText("Difference:");

        chartImpactSection2Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Chart"));

        javax.swing.GroupLayout chartImpactSection2PanelLayout = new javax.swing.GroupLayout(chartImpactSection2Panel);
        chartImpactSection2Panel.setLayout(chartImpactSection2PanelLayout);
        chartImpactSection2PanelLayout.setHorizontalGroup(
            chartImpactSection2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chartImpactSection2PanelLayout.setVerticalGroup(
            chartImpactSection2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout co2ImpactResultsContainerLayout = new javax.swing.GroupLayout(co2ImpactResultsContainer);
        co2ImpactResultsContainer.setLayout(co2ImpactResultsContainerLayout);
        co2ImpactResultsContainerLayout.setHorizontalGroup(
            co2ImpactResultsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(co2ImpactResultsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(co2ImpactResultsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(co2ImpactResultsContainerLayout.createSequentialGroup()
                        .addComponent(differenceImpactLabel)
                        .addGap(0, 232, Short.MAX_VALUE))
                    .addComponent(chartImpactSection2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        co2ImpactResultsContainerLayout.setVerticalGroup(
            co2ImpactResultsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(co2ImpactResultsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(differenceImpactLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chartImpactSection2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        resultsSection2PanelContainer.add(co2ImpactResultsContainer);

        btnS2Back.setText("Back");
        btnS2Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS2BackActionPerformed(evt);
            }
        });

        btnS2Next.setText("Next");
        btnS2Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS2NextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnContainerSection2PanelLayout = new javax.swing.GroupLayout(btnContainerSection2Panel);
        btnContainerSection2Panel.setLayout(btnContainerSection2PanelLayout);
        btnContainerSection2PanelLayout.setHorizontalGroup(
            btnContainerSection2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnContainerSection2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnS2Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnS2Next)
                .addContainerGap())
        );
        btnContainerSection2PanelLayout.setVerticalGroup(
            btnContainerSection2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnContainerSection2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnContainerSection2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnS2Back)
                    .addComponent(btnS2Next))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sldS2UsagePercent.setMajorTickSpacing(10);
        sldS2UsagePercent.setMaximum(30);
        sldS2UsagePercent.setMinimum(-30);
        sldS2UsagePercent.setMinorTickSpacing(5);
        sldS2UsagePercent.setPaintTicks(true);
        sldS2UsagePercent.setValue(0);
        sldS2UsagePercent.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        adjustUsageLabel.setText("Adjust Usage ");

        javax.swing.GroupLayout contentPanelSection2Layout = new javax.swing.GroupLayout(contentPanelSection2);
        contentPanelSection2.setLayout(contentPanelSection2Layout);
        contentPanelSection2Layout.setHorizontalGroup(
            contentPanelSection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelSection2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelSection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adjustUsageSliderContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultsSection2PanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnContainerSection2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(presetsSection2PanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelSection2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(adjustUsageLabel)
                        .addGap(18, 18, 18)
                        .addComponent(sldS2UsagePercent, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Section2TitleContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        contentPanelSection2Layout.setVerticalGroup(
            contentPanelSection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelSection2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Section2TitleContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPanelSection2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelSection2Layout.createSequentialGroup()
                        .addComponent(adjustUsageSliderContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(sldS2UsagePercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelSection2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(adjustUsageLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(presetsSection2PanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resultsSection2PanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnContainerSection2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPanelSection2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPanelSection2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdoS2PresetWinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoS2PresetWinterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoS2PresetWinterActionPerformed

    private void btnS2BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS2BackActionPerformed
        ui.MainFrame mf = (ui.MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (mf != null) {
        mf.goSection1();
        }
    }//GEN-LAST:event_btnS2BackActionPerformed

    private void btnS2NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS2NextActionPerformed
        ui.MainFrame mf = (ui.MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (mf != null) {
        mf.goSection3();
        }
    }//GEN-LAST:event_btnS2NextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Section2TitleContainer;
    private javax.swing.JLabel adjustUsageLabel;
    private javax.swing.JPanel adjustUsageSliderContainer;
    private javax.swing.JPanel annualCostResultsContainer;
    private javax.swing.JPanel btnContainerSection2Panel;
    private javax.swing.JButton btnS2Back;
    private javax.swing.JButton btnS2Next;
    private javax.swing.JPanel chartCostSection2Panel;
    private javax.swing.JPanel chartImpactSection2Panel;
    private javax.swing.JPanel co2ImpactResultsContainer;
    private javax.swing.JPanel contentPanelSection2;
    private javax.swing.JLabel differenceCostLabel;
    private javax.swing.JLabel differenceImpactLabel;
    private javax.swing.ButtonGroup grpS2Presets;
    private javax.swing.JLabel presetsLabelSection2Panel;
    private javax.swing.JPanel presetsSection2PanelContainer;
    private javax.swing.JRadioButton rdoS2PresetNewAppliance;
    private javax.swing.JRadioButton rdoS2PresetSummer;
    private javax.swing.JRadioButton rdoS2PresetWinter;
    private javax.swing.JPanel resultsSection2PanelContainer;
    private javax.swing.JSlider sldS2UsagePercent;
    private javax.swing.JLabel titleSection2;
    // End of variables declaration//GEN-END:variables
}
